# redirect HTTP lên HTTPs
server {
    listen 80;
    server_name localhost;

    return 301 https://$host:5174$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # cert
    ssl_certificate     /certs/kong.crt;
    ssl_certificate_key /certs/kong.key;

    # TLS 1.3
    ssl_protocols TLSv1.3;
    ssl_conf_command Ciphersuites TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;  

    # Các header bảo mật 
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;  

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
