server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: '/api-gateway'
        target_label: service
        replacement: kong
      - source_labels: [__meta_docker_container_name]
        regex: '/api-backend'
        target_label: service
        replacement: fastapi
      - source_labels: [__meta_docker_container_name]
        regex: '/opa'
        target_label: service
        replacement: opa
      - source_labels: [__meta_docker_container_name]
        regex: '/keycloak'
        target_label: service
        replacement: keycloak